config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
	get 'tags/:tag', to: 'articles#index', as: :tag
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
	resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	acts_as_taggable_on :tags
  belongs_to :user
	default_scope -> { order(created_at: :desc) }
	has_rich_text :content
	validates :user_id, presence: true
	validates :subject, presence: true
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, dependent: :destroy
  attr_accessor :remember_token
  validates :name, presence:true, length: {maximum: 50 }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    # 渡された文字列のハッシュ値を返す(fixture向け)
    def digest(string) #User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                     BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token #User.new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

	# 試作feedの定義
	def feed
		Article.where("user_id = ?", id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

	private

		# ユーザのログインを確認する
		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "ログインが必要なコンテンツです。"
				redirect_to login_url
			end
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :logged_in_user
	before_action :correct_user, only: [:edit, :destroy]
	before_action :admin_user, except: [:index, :show]

	def index
		@tags = Article.tags_on(:tags)
		if params[:tag]
			@articles = Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 10)
		else
			@articles = Article.paginate(page: params[:page], per_page: 10)
		end
	end

	def create
		@article = current_user.articles.build(article_params)
		if @article.save
			flash[:success] = "記事を作成しました。"
			redirect_to root_url
		else
			@feed_items = current_user.feed.paginate(page: params[:page], per_page: 10)
			render 'articles#new'
		end
	end

	def new
		if logged_in?
		@article = current_user.articles.build
		@feed_items = current_user.feed.paginate(page: params[:page], per_page: 10)
		end
	end

	def edit
		@article = Article.find(params[:id])
		@all_tags = Article.tags_on(:tags)
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			flash[:success] = "記事を更新しました。"
			redirect_to root_url
		else
			render 'edit'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def destroy
		@article.destroy
		flash[:success] = "記事を削除しました。"
		redirect_to root_url
	end

	private

		def article_params
			params.require(:article).permit(:subject, :content, :tag_list)
		end

		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "ログインが必要なコンテンツです。"
				redirect_to login_url
			end
		end

		def correct_user
			@article = current_user.articles.find_by(id: params[:id])
			redirect_to root_url if @article.nil?
		end

		def admin_user
			redirect_to(root_url) unless current_user.admin?
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or root_url
    else
      flash.now[:danger] = 'ユーザ名またはパスワードが間違っています。'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper

	before_action :logged_in_user
  before_action :admin_user

  def index
    @users =User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
		@articles = @user.articles.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザを作成しました。"
      redirect_to users_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールを変更しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザを削除しました。"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :admin)
    end

		#ユーザのログインを確認する
		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "ログインが必要なコンテンツです。"
				redirect_to login_url
			end
		end

    # 正しいユーザかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "開発村通信"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 現在ログイン中のユーザを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # 渡されたユーザがカレントユーザであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end

  # ユーザがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # 記憶したURL(もしくはデフォルト値)にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<%= link_to article_path(article), class: 'list-group-item list-group-item-action' do %>
	<%= tag.div do %>
		<%= tag.h4 do %>
			<%= article.subject %>
		<% end %>
	<% end %>
	<%= tag.div do %>
		<% article.tag_list.each do |tags| %>
			<%= tag.span class: 'border mx-1 bg-light' do %>
				<%= tags %>
			<% end %>
		<% end %>
	<% end %>
	<%= tag.div do %>
		<%= article.created_at.strftime('%Y/%m/%d') %>
	<% end %>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "Update") %>
<% provide(:button_text, '更新') %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.div class: 'col-auto' do %>
		<%= tag.h1 "記事を編集" %>
	<% end %>
<% end %>

<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.div class: 'col-lg-8' do %>
		<%= form_with(model: @article, local: true) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= render 'shared/article_form' %>
		<% end %>
	<% end %>
<% end %>

app/views/articles/index.html.erb
<% provide(:title, 'Home') %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.h1 "記事一覧", class: 'col-auto' %>
<% end %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.div class: 'col-lg-8' do %>
		<%= tag.div class: 'list-group' do %>
			<%= render @articles %>
		<% end %>
		<%= will_paginate %>
	<% end %>
	<%= tag.div class: 'col-lg-2' do %>
		<%= tag.div class: 'border rounded' do %>
			<%= tag.h4 "タグ", class: 'mx-1 my-1' %>
			<%= tag.ul class: 'list-unstyled mx-2' do %>
				<% @tags.each do |tags| %>
					<%= tag.li do %>
						<%= link_to "#{tags.name}(#{tags.taggings_count})", tag_path(tags.name) %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
		<%= tag.div do %>
			<a class="twitter-timeline" href="https://twitter.com/kougakufes?ref_src=twsrc%5Etfw" data-height="600">Tweets by 2021kougakusai</a>
			<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
		<% end %>
	<% end %>
<% end %>

app/views/articles/new.html.erb
<% provide(:title, "New") %>
<% provide(:button_text, "投稿") %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.h1 "記事を作成", class: 'col-auto' %>
<% end %>
<%= tag.div class: 'row mx-1' do %>
	<%= tag.div class: 'col-lg-6 offset-lg-2' do %>
		<%= tag.div class: 'border border-top-0 border-left-0 border-right-0 py-2' do %>
			<%= render 'shared/user_info' %>
		<% end %>
			<%= render 'shared/article_form' %>
	<% end %>
	<%= tag.div class: 'col-lg-3' do %>
		<%= tag.div class: 'my-2' do %>
			<%= tag.h3 "今までの投稿" %>
		<% end %>
		<%= render 'shared/feed' %>
	<% end %>
<% end %>

app/views/articles/show.html.erb
<% provide(:title, "#{@article.subject}") %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.h1 class: 'col-lg-8' do %>
		<%= @article.subject %>
	<% end %>
<% end %>
<%= tag.div class: 'row justify-content-center mx-1 my-2' do %>
	<%= tag.div class: 'col-lg-8 border border-top-0 border-left-0 border-right-0 pb-1' do %>
		<%= tag.div do %>
			<%= @article.user.name %>
		<% end %>
		<%= tag.div class: 'nav' do %>
			<%= tag.span "タグ:", class: 'nav-item' %>
			<% @article.tag_list.each do |tags| %>
				<%= tag.span class: 'nav-item ml-1' do %>
					<%= tags %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

<%= tag.div class: 'row justify-content-center mx-1 my-1' do %>
	<%= tag.div class: 'col-lg-8' do %>
		<% if current_user?(@article.user) && current_user.admin? %>
			<%= link_to "編集", edit_article_path(@article), class: "btn btn-primary" %>
			<%= link_to "削除", @article, method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-primary" %>
		<% end %>
	<% end %>
<% end %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.div class: 'col-lg-8' do %>
		<%= @article.content %>
	<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<%= tag.footer class: 'border border-bottom-0 border-right-0 border-left-0 mt-3' do %>
	<%= tag.small "こうがく祭実行委員会2021", class: 'ml-5' %>
	<%= tag.span class: 'float-right mr-5' do %>
		<%= link_to fa_icon("twitter 2x"), 'https://twitter.com/kougakufes' %>
	<% end %>
<% end %>

app/views/layouts/_header.html.erb
<%= tag.nav class: 'navbar bg-primary' do %>
  <%= tag.div class: 'col-10' do %>
	  <%= link_to "開発村通信", root_path, id: "logo", class: "navbar-brand text-light mx-5" %>
  <% end %>
  <%= tag.div id: 'nav-drawer', class: 'col-2' do %>
    <%= tag.input id: 'nav-input', type: 'checkbox', class: 'nav-unshown' %>
    <%= tag.label id: 'nav-open', for: 'nav-input' do %>
      <%= tag.span %>
    <% end %>
    <%= tag.label class: 'nav-unshown', id: 'nav-close', for:'nav-input' %>
    <%= tag.ul id: 'nav-content' do %>
      <% if logged_in? %>
        <%= tag.li do %>
          <%= link_to "ログアウト", logout_path, method: :delete %>
        <% end %>
        <%= tag.li do %>
          <%= link_to "記事一覧", root_path %>
        <% end %>
        <% if current_user.admin? %>
          <%= tag.li do %>
            <%= link_to "ユーザ一覧", users_path %>
          <% end %>
          <%= tag.li do %>
            <%= link_to "マイページ", current_user %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if Lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
		<%= tag.div class: 'container-flood' do %>
    	<%= render 'layouts/header' %>
		<% end %>
		<%= tag.div class: 'container-flood pt-3' do %>
			<%= tag.div class: 'col-auto' do %>
      	<% flash.each do |message_type, message| %>
        	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      	<% end %>
			<% end %>
		<% end %>
		<%= tag.div class: 'container-flood' do %>
			<%= tag.div class: 'col-auto' do %>
      	<%= yield %>
			<% end %>
		<% end %>
		<%= tag.div class: 'container-flood' do %>
			<%= tag.div class: 'col-auto' do %>
      	<%= render 'layouts/footer' %>
				<%= tag.div class: 'mx-5 px-5' do %>
      		<%= debug(params) if Rails.env.development? %>
				<% end %>
			<% end %>
		<% end %>
  </body>
</html>

app/views/shared/_article_form.html.erb
<%= form_with(model: @article, local: true) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= tag.div class: 'form-group mt-2 col-auto' do %>
		<%= f.label :subject, "タイトル" %>
		<%= f.text_area :subject, class: "form-control"%>
	<% end %>

	<%= tag.div class: 'form-group mt-2 col-auto' do %>
		<%= f.label :tag_list, "タグ" %>
		<%= f.text_field :tag_list, value: @article.tag_list.join(','), placeholder: "tag1,tag2,...", class: "form-control" %>
	<% end %>

	<%= tag.div class: 'form-group mt-2 col-auto' do %>
		<%= f.label :content, "本文" %>
		<%= f.rich_text_area :content %>
	<% end %>

	<%= f.submit yield(:button_text), class: "btn btn-primary btn-block mt-3 col-auto" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      エラーが<%= object.errors.count %>つあります。
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="articles">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate @feed_items, params: { controller: :articles, action: :new } %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィールを見る", current_user %></span>
<span><%= pluralize(current_user.articles.count, "本の記事を投稿しています") %></span>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

	<%= tag.div class: 'form-group mt-2 col-auto' do %>
  	<%= f.label :name, "ユーザ名" %>
  	<%= f.text_field :name, class: 'form-control' %>
	<% end %>

	<%= tag.div class: 'form-group mt-2 col-auto' do %>
  	<%= f.label :password, "パスワード" %>
  	<%= f.password_field :password, class: 'form-control' %>
	<% end %>

	<%= tag.div class: 'form-group mt-2 col-auto' do %>
  	<%= f.label :password_confirmation, "パスワード(確認のため再度入力してください)" %>
  	<%= f.password_field :password_confirmation, class: 'form-control' %>
	<% end %>

	<%= tag.div class: 'form-check mt-2 col-auto' do %>
		<%= f.label :admin, "管理者権限を付与する", class: 'form-check-label' %>
		<%= f.check_box :admin, class: 'form-check-input' %>
	<% end %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block mt-3 col-auto" %>
<% end %>

app/views/users/_user.html.erb
<%= tag.div class: 'list-group-item list-group-item-action' do %>
	<%= link_to user.name, user %>
	<% if current_user.admin? %>
		<% if !user.admin? || current_user == user %>
    	<%= link_to "編集", edit_user_path(user), class: 'btn btn-primary ml-2' %>
    	<%= link_to "削除", user, class: 'btn btn-primary ml-1', method: :delete, data: { confirm: "ユーザを削除しますか？" } %>
		<% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Update Profile") %>
<% provide(:button_text, '変更を保存する') %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.h1 "プロフィールを変更", class: 'col-auto' %>
<% end %>

<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.div class: 'col-lg-6' do %>
    <%= render 'form' %>
	<% end %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.h1 "ユーザ一覧", class: 'col-auto' %>
<% end %>

<%= tag.div class: 'row justify-content-center mx-1 my-1' do %>
	<%= tag.div class: 'col-lg-8' do %>
		<%= link_to "新規ユーザを作成", signup_path, class: 'btn btn-primary' %>
	<% end %>
<% end %>
<%= tag.div class: 'row justify-content-center mx-1 my-1' do %>
	<%= tag.div class: 'col-lg-8' do %>
		<%= will_paginate %>
		<%= tag.div class: 'list-group' do %>
  		<%= render @users %>
		<% end %>
		<%= will_paginate %>
	<% end %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'New User') %>
<% provide(:button_text, 'ユーザを作成する') %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.h1 "新規ユーザ作成", class: 'col-auto' %>
<% end %>

<%= tag.div class: 'row justify-content-center mx-1' do %>
  <%= tag.div class: 'col-lg-6' do %>
    <%= render 'form' %>
	<% end %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.h1 class: 'col-auto' do %>
		<%= @user.name %>
	<% end %>
<% end %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.div class: 'col-lg-8' do %>
		<% if current_user == @user %>
			<%= link_to "新規記事を作成", new_article_path, class: 'btn btn-primary' %>
		<% end %>
	<% end %>
<% end %>
<%= tag.div class: 'row justify-content-center mx-1' do %>
	<%= tag.div class: 'col-lg-8' do %>
		<% if @user.articles.any? %>
			<%= tag.h3 do %>
				投稿した記事 (<%= @user.articles.count %>)
			<% end %>
			<%= tag.div class: 'list-group' do %>
				<%= render @articles %>
			<% end %>
			<%= will_paginate @articles %>
		<% end %>
	<% end %>
<% end %>